carpCoreVersion=1.2.1

springBootVersion=4.0.7
#springCloudVersion=2023.0.1
springDependencyManagementVersion=1.1.7
#springCloudStarterVersion=4.1.2
springMockkVersion=5.0.1

kotlinVersion=2.4.0
kotlinDatetimeVersion=0.6.1
kotlinCoroutinesVersion=1.9.0
serializationJSONVersion=1.7.3
detektVersion=1.23.8
ktlintVersion=12.2.0

#keycloakVersion=24.0.4
springAddonsVersion=9.1.4
hibernateTypesVersion=3.15.3
commonsIOVersion=2.21.0
commonsCompressVersion=1.28.0
rsqlParserVersion=2.1.0
flywayVersion=10.20.0
guavaVersion=33.4.8-jre
awsSDKVersion=2.34.0
springdocVersion=3.0.3
okhttpVersion=4.12.0
gsonVersion=2.13.1
