package dk.cachet.carp.webservices.selfsignup.controller

import dk.cachet.carp.common.application.UUID
import dk.cachet.carp.webservices.common.constants.PathVariableName
import dk.cachet.carp.webservices.selfsignup.controller.SelfSignupAdminController.Companion.SELF_SIGNUP
import dk.cachet.carp.webservices.selfsignup.dto.EnableSelfSignupRequestDto
import dk.cachet.carp.webservices.selfsignup.dto.SelfSignupConfigResponseDto
import dk.cachet.carp.webservices.selfsignup.service.SelfSignupService
import io.swagger.v3.oas.annotations.Operation
import jakarta.validation.Valid
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Logger
import org.springframework.http.HttpStatus
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.web.bind.annotation.*

/** Admin management of a study's semi-self-signup configuration - enable/reconfigure, end, and inspect. */
@RestController
@RequestMapping(SELF_SIGNUP)
class SelfSignupAdminController(
    private val selfSignupService: SelfSignupService,
) {
    companion object {
        private val LOGGER: Logger = LogManager.getLogger()
        const val SELF_SIGNUP = "/api/studies/{${PathVariableName.STUDY_ID}}/self-signup"
    }

    @Operation(
        summary = "Enable or reconfigure self-signup",
        description =
            "Enables Kahoot-style self-signup for the study, or reconfigures it if already enabled or " +
                "ended before. The study must be live and the given participant role must exist on its " +
                "protocol. A short code is generated once, on first enable, and is never regenerated by " +
                "later calls - it survives an enable -> end -> re-enable cycle. maxParticipants is a " +
                "lifetime cap and may be raised or lowered on a later call.",
    )
    @PutMapping
    @PreAuthorize("canManageStudy(#studyId) or canLimitedManageStudy(#studyId)")
    suspend fun enable(
        @PathVariable(PathVariableName.STUDY_ID) studyId: UUID,
        @Valid @RequestBody request: EnableSelfSignupRequestDto,
    ): SelfSignupConfigResponseDto {
        LOGGER.info("Start PUT: $SELF_SIGNUP")
        return selfSignupService.enable(studyId, request)
    }

    @Operation(
        description =
            "Current self-signup config/status for the study (short code, enabled, cap, " +
                "current count), or null if self-signup has never been enabled.",
    )
    @GetMapping
    @PreAuthorize("canManageStudy(#studyId) or canLimitedManageStudy(#studyId)")
    suspend fun getConfig(
        @PathVariable(PathVariableName.STUDY_ID) studyId: UUID,
    ): SelfSignupConfigResponseDto? {
        LOGGER.info("Start GET: $SELF_SIGNUP")
        return selfSignupService.getConfig(studyId)
    }

    @Operation(
        description =
            "Ends self-signup for the study: flips it disabled. The short code and cumulative " +
                "participant count are kept, so re-enabling later resumes under the same code.",
    )
    @DeleteMapping
    @ResponseStatus(HttpStatus.OK)
    @PreAuthorize("canManageStudy(#studyId) or canLimitedManageStudy(#studyId)")
    suspend fun end(
        @PathVariable(PathVariableName.STUDY_ID) studyId: UUID,
    ): SelfSignupConfigResponseDto {
        LOGGER.info("Start DELETE: $SELF_SIGNUP")
        return selfSignupService.end(studyId)
    }
}
