package dk.cachet.carp.webservices.selfsignup.service

import dk.cachet.carp.common.application.UUID
import dk.cachet.carp.webservices.selfsignup.dto.EnableSelfSignupRequestDto
import dk.cachet.carp.webservices.selfsignup.dto.SelfSignupConfigResponseDto

/** Admin-facing management of a study's semi-self-signup configuration. Runs under an authenticated,
 * study-management-authorized request. */
interface SelfSignupService {
    /**
     * Enable self-signup for [studyId], or reconfigure it if already enabled/ended before. The study must
     * be live and [request].participantRoleName must exist on its protocol. A short code is generated once,
     * on first enable, and is never regenerated by later calls to this method.
     */
    suspend fun enable(
        studyId: UUID,
        request: EnableSelfSignupRequestDto,
    ): SelfSignupConfigResponseDto

    /** End self-signup for [studyId]: flips it disabled, keeps the short code and cumulative count. */
    suspend fun end(studyId: UUID): SelfSignupConfigResponseDto

    /** Current self-signup config/status for [studyId], or `null` if never enabled. */
    suspend fun getConfig(studyId: UUID): SelfSignupConfigResponseDto?
}
