name: verify pull requests

on:
  pull_request:
    branches:
      - develop, testing, master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build and test
        run: ./gradlew build