name: verify pull requests

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build and test
        run: ./gradlew build